### ISSUE TITLE
序列化的时候 "&" 会变成 "u0026"

### ISSUE THREAD

**Issue by zhaowq32** [Andrew-M-C/go.jsonvalue#11]
jsonvalue有escapehtml选项么

**Comment by Andrew-M-C** [comment]
你需要什么样的 escape 呢？对于 jsonvalue 来说，所有大于 128 的字符都会序列化为 \uXXXX 的格式哦

**Comment by zhaowq32** [comment]
json库的Encoder提供了SetEscapeHTML函数，控制是否转译。jsonvalue能否添加一下disable escapehtml的配置。

**Comment by Andrew-M-C** [comment]
emm... 也是可以考虑的... 不过如果要支持的话就最好能够支持较为完整的 encoder 模式
我考察一下对逻辑的影响。今年只剩几天了，估计来不及。我一月份结束之前给个定论吧

@zhaowq32

**Comment by Andrew-M-C** [comment]
备注一下官方的接口： https://pkg.go.dev/encoding/json#Encoder

**Comment by Andrew-M-C** [comment]
@zhaowq32 考察了一下，纯粹 SetEscapeHTML 函数的话，支持还是比较快的。。。

**Comment by Andrew-M-C** [comment]
@zhaowq32 我实现了，就在 master 分支上。您测试下？如果 OK，我就打一个 alpha 版的 tag 预发布～～

**Comment by zhaowq32** [comment]
不好意思，已测试通过，无问题。感谢您的辛勤工作。

**Comment by Andrew-M-C** [comment]
不客气不客气～～
