### ISSUE TITLE
字符串中汉字与网址问题

### ISSUE THREAD

**Issue by jyzhkj** [Andrew-M-C/go.jsonvalue#13]
v.SetInt(9).At("result")
v.SetString("测试").At("result2")
v.SetString("http://abcd.com").At("result3")
ss := v.MustMarshalString(jsonvalue.OptEscapeHTML(false))

fmt.Println(ss)

实际结果：
{"result":9,"result2":"\u6D4B\u8BD5","result3":"http:\/\/abcd.com"

期待结果：
{"result":9,"result2":"测试","result3":"http://abcd.com"}

怎么处理？

**Comment by Andrew-M-C** [comment]
这没问题呀

**Comment by Andrew-M-C** [comment]
`{"result":9,"result2":"\u6D4B\u8BD5","result3":"http://abcd.com"}`

这是正确的，对端也能够正确解析出来。这是标准的 JSON 编码格式

**Comment by Andrew-M-C** [comment]
我之所以设定默认逻辑为 ascii，是因为这个：

- 当时对接合作伙伴的系统时，对方是挺老的 php 架构，貌似是大端的类似 eascii 编码，简单而言就是对 ascii 还是如常，但是针对 > 127 的就加一个字节
- 发现这个问题后，就与对方开发解释 utf-8 是什么，但是很遗憾，对方听不懂
- 后面我就干脆把 encoding 改成了 ascii，在对方依然没搞明白 utf-8 是什么的时候，接口马上就通了

所以，我意识到：即便不同，但是只要换成 ascii，不论什么 json 库都还是支持的，兼容性上肯定没问题，而且是最高的兼容性。

不过缺点是，如果有大量非 ascii 字符的话，那么编码会比较长，浪费带宽。我把这个作为 v1.2.1 的 feature 吧。

**Comment by Andrew-M-C** [comment]
v1.2.1-beta 已实现，关闭此 issue

**Comment by Andrew-M-C** [comment]
https://github.com/Andrew-M-C/go.jsonvalue/tree/v1.2.1-beta
