### ISSUE TITLE
不支持范型array就是鸡肋，没什么用的库（已回复）

### ISSUE THREAD

**Issue by harryhan1989** [Andrew-M-C/go.jsonvalue#14]

**Comment by Andrew-M-C** [comment]
这个小库也有批评啦？可喜可贺可喜可贺

既然你说到了泛型，我正好说一下这个库的设计初衷，以及后续的计划吧

## 设计初衷

首先是设计初衷。Jsonvalue 的设计初衷有两个: 

- 需要处理一些类型不确定的 JSON 数据，因此不能用 struct。用原生的话，必须用 map[string]interface{}，但是这种方案要自己处理 interface{}，太难受了。因此借鉴了 cJSON 开发了这个库
- 一些云 API 的 JSON 格式很奇葩，比如说需要判断是否包含某个对象，并且判断对象中的某个字段是否为某个值。不论是要构造，还是解析，都很难受。因此在 jsonvalue 里就加入了深层 path 解析和配置的功能（你可以参考 Get 和 Set().At() 函数的那一长串参数）

## 应用场景

然后说说这个库的应用场景吧。天下没有哪一个代码是万金油，针对不同的应用场景，选取最合适的才是王道。这里我专门针对我常用的几个 JSON 库进行了比较分析:《[Go 语言原生的 json 包有什么问题？如何更好地处理 JSON 数据？](https://segmentfault.com/a/1190000039957766)》。

在文中我也没推荐在所有场景下使用 jsonvalue。Jsonvalue 最典型和不可替代的应用场景是下面几个:

- 快速构建复杂的 JSON 并序列化——我观察了一下使用这个库的其他 repo，大部分应用场景是这个，这也是很标准的设计初衷
- 全量解析并 dump/转换 KV——这个一般在离线清洗的应用场景中，在我们公司内部的应用中有这么搞的
- 部分非法的 JSON 值处理——这个主要是针对 float 的，在 JSON 中不支持双精度数的 Inf 和 N/A，但是 Go 的 struct 不可避免地会出现这个数（特别是在算法领域）。我们遇到了，所以就借用 jsonvalue 这个壳来解决

## 关于泛型

简单结论：泛型是迟早要支持的，到时可能会以 jsonvalue v2 的方式推出。

但是这件事情我不急。为什么呢？

- Go 泛型的语法依然充满了争议，不排除以后 Go 2 对泛型再做大刀阔斧的调整。
- 虽然 1.18 号称正式支持泛型，但是 1.18 本身还不太稳定，暂时不建议在生产环境上使用
  - 我们内部的 Go 团队有一个不成文的共识: 除非是重大漏洞修复，否则生产环境的 Go 版本大致最新的落后 0.2 是比较合适的。
  - 在版本上，jsonvalue 不是一个激进的库，它是面向生产环境的——这也是为什么我那么执着地要把单测覆盖率提升到 99.5% 以上的主要原因
- 在使用体验上，jsonvalue 已经尽量降低对类型的依赖了。最典型的就是 Set().At() 和 Get() 的参数，可以让使用者无需区分 string 和 int 参数
  - 下一步，jsonvalue v1.3.0 会进一步魔改 Set() 函数，参数将会变成 interface{}，这样一来任何类型都可以支持了，那这体验就真的与泛型无异——当然，这其实是基于另一个 feature 的附属品而已～～

**Comment by Andrew-M-C** [comment]
@harryhan1989 推荐你尝试一下开发中的 [feature/v1.3.0](https://github.com/Andrew-M-C/go.jsonvalue/tree/feature/v1.3.0)，前文提到的对 Set 函数的魔改已经完成，同时支持的还有 Append 和 Insert 函数。允许传入任何参数，包括你说的 array，你会获得与泛型相同的体验。

[这个单测函数](https://github.com/Andrew-M-C/go.jsonvalue/blob/feature/v1.3.0/set_test.go#L173) 也很好地做了一个示例，这里我传入的是 `[]interface{}` 类型，比你说的泛型 array 更加自由

**Comment by Andrew-M-C** [comment]
已于 v1.3.0 支持
