### ISSUE TITLE
注释、文档例程和实际代码有些出入

### ISSUE THREAD

**Issue by xray-bit** [Andrew-M-C/go.jsonvalue#18]
注释、文档例程是否和实际代码有些出入。实际代码返回了2个参数，文档和注释看起来是只返回1个参数。

https://github.com/Andrew-M-C/go.jsonvalue/blob/a326e593467b1dde35b17d7dda2f283f073c9a80/get.go#L141-L146

https://github.com/Andrew-M-C/go.jsonvalue/blob/a326e593467b1dde35b17d7dda2f283f073c9a80/docs/zh-cn/02_quick_start.md?plain=1#L33-L37

**Comment by Andrew-M-C** [comment]
噢，确实是错了~这里应该是

```go
// ...
s := jsonvalue.MustUnmarshalString(s).MustGet("obj", "obj", "obj", "str").String()
// ...
```

我在分支 [feature/v1.3.2](https://github.com/Andrew-M-C/go.jsonvalue/tree/feature/v1.3.2) 里改，这个分支只修了一个小bug，还没发布呢



非常感谢反馈！！！

**Comment by Andrew-M-C** [comment]
已在 v1.3.2 修订，已发布
