### ISSUE TITLE
在GIN中如何使用jsonvalue

### ISSUE THREAD

**Issue by NumboZhang** [Andrew-M-C/go.jsonvalue#2]
在GIN里会使用以下代码对返回值进行赋值
`	c.JSON(http.StatusOK, gin.H{
		"code": "A00000",
		"msg":  "Operation Success",
		"data": gin.H{
			"record": map[string]interface{}{},
		},
	})`
这里的gin.H是一个map
`type H map[string]interface{}`
尝试了很久，都没有能够使用jsonvalue转换为这个格式，想请教下如何能做到呢？
顺便这库很好用，点个赞~
希望不要像fastjson那样出漏洞就好~

**Comment by Andrew-M-C** [comment]
@NumboZhang 解决方法是：不使用 c.JSON()
