### ISSUE TITLE
I suggest that the Chinese notes in the project should be changed to English ones.

### ISSUE THREAD

**Issue by xiangyuanliu** [Andrew-M-C/go.jsonvalue#21]
I'm glad to find the tool I want after searching for a long time.
Many companies outside China will add Chinese char inspection to the project because some stubborn users think that Chinese products are not reliable enough.
Please let us avoid this risk before we change their minds.

**Comment by Andrew-M-C** [comment]
Sure! I am glad to provide English version for this repo. 

Godocs in English are already provieded. But English wiki needs some time. 
However, if required, I will do it!

Task scheduled!

**Comment by Andrew-M-C** [comment]
Oops, after re-reading your issue, do you mean that ALL Chinese content of godoc should be REMOVED? @xiangyuanliu

**Comment by Andrew-M-C** [comment]
English wiki added at v1.3.3. Done
