### ISSUE TITLE
能否支持全局默认Option的修改？

### ISSUE THREAD

**Issue by xray-bit** [Andrew-M-C/go.jsonvalue#25]
首先这个库真的很好用，很顺手。

有一点在使用中显得比较繁琐的事情，就是对于默认 Option 无法满足需求的情况下，每次都要在 Marshal/Unmarshal 时打一堆选项。
有没有可能提供一个接口修改默认的 Option，这样只需要设置一次 Option。

**Comment by Andrew-M-C** [comment]
有的有的～～～

**Comment by xray-bit** [comment]
> 有的～～～参见 1.12 的 [new feature - 支持覆盖默认序列化配置](https://github.com/Andrew-M-C/go.jsonvalue/blob/master/docs/zh-cn/15_1_12_new_feature.md#%E6%94%AF%E6%8C%81%E8%A6%86%E7%9B%96%E9%BB%98%E8%AE%A4%E5%BA%8F%E5%88%97%E5%8C%96%E9%85%8D%E7%BD%AE)。我下次把这个写入 wiki 正文中而不是放在 change log 哈

好的，谢谢 <3
