### ISSUE TITLE
MustGet("key").Int()异常

### ISSUE THREAD

**Issue by luomoxu** [Andrew-M-C/go.jsonvalue#27]
```
package main

import (
	"fmt"
	jsonvalue "github.com/Andrew-M-C/go.jsonvalue"
)

func main() {
	raw := `{"number":""}`
	n := jsonvalue.MustUnmarshalString(raw)
	fmt.Println(n.MustGet("number").Int())
}
```
执行会报错
`panic: runtime error: index out of range [0] with length 0`

这个是设计就是如此还是非预期错误？

**Comment by Andrew-M-C** [comment]
呀这肯定是错误了，我处理下～～

**Comment by Andrew-M-C** [comment]
@luomoxu 
您可以试一下
`go get github.com/Andrew-M-C/go.jsonvalue@feature/v1.3.6`
或者
`go get github.com/Andrew-M-C/go.jsonvalue@b9b1257`

这个分支修复了俩 bug，过段时间没有新 bug 的话我就打 tag

**Comment by Andrew-M-C** [comment]
Fixed at Tag v1.3.6
