### ISSUE TITLE
序列化的时候 "/" 会变成 "\/"

### ISSUE THREAD

**Issue by crazytaxi824** [Andrew-M-C/go.jsonvalue#3]
`
func Test_JsonVale(t *testing.T) {
	var m = map[string]interface{}{
		"abc/123": "123",
	}
	v := jsonvalue.NewObject(m)
	s, _ := v.MarshalString()
	t.Log(s)
}
`

expect {"abc/123":"123"}
get {"abc\\/123":"123"}

**Comment by Andrew-M-C** [comment]
@crazytaxi824 按照 JSON 标准，/ 是需要转义的，具体可以参考以下标准书的第九章：**9 String**
https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

也可以参考 json.org 的首页上关于需要转义的字符的图：
![image](https://user-images.githubusercontent.com/6083108/122842436-f7d83f00-d32f-11eb-98d7-00450f3e06cb.png)

所以，从 Marshal 的角度，jsonvalue 的处理方法是没错的。

不过你这一说确实让我发现了，encoding/json 并没有按照 json 标准的要求去转义；同时，encoding/json 也支持两种转义方式，我后面也改成支持两种模式吧，改好了之后我会更新一下这个 issue 的状态~~

**Comment by Andrew-M-C** [comment]
@crazytaxi824 我确认了一下，目前 jsonvalue 在 unmarshal 的时候就已经是支持 "/" 和 "\/" 两种转义方式的。那我把这个 issue close 了吧
