### ISSUE TITLE
请大佬看看这个怎么出错了，谢谢！

### ISSUE THREAD

**Issue by gitv2ray** [Andrew-M-C/go.jsonvalue#8]
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/Andrew-M-C/go.jsonvalue"
)

func main() {
	fmt.Println("Hello World!")

	strJson := []byte(`{"tunnels":[{"name":"command_line","uri":"/api/tunnels/command_line","public_url":"https://11111.ngrok.io","proto":"https","config":{"addr":"http://localhost:11111","inspect":true},"metrics":{"conns":{"count":1,"gauge":0,"rate1":5.456067032277228e-19,"rate5":0.0000016821504265361616,"rate15":0.00008846097772300972,"p50":8287268034,"p90":8287268034,"p95":8287268034,"p99":8287268034},"http":{"count":5,"rate1":2.5535363027836646e-18,"rate5":0.000008299538128664852,"rate15":0.0004403445395661658,"p50":427625,"p90":600127,"p95":600127,"p99":600127}}},{"name":"command_line (http)","uri":"/api/tunnels/command_line%20%28http%29","public_url":"http://11111.ngrok.io","proto":"http","config":{"addr":"http://localhost:11111","inspect":true},"metrics":{"conns":{"count":0,"gauge":0,"rate1":0,"rate5":0,"rate15":0,"p50":0,"p90":0,"p95":0,"p99":0},"http":{"count":0,"rate1":0,"rate5":0,"rate15":0,"p50":0,"p90":0,"p95":0,"p99":0}}}],"uri":"/api/tunnels"}`)
	j, err := jsonvalue.Unmarshal(strJson)
	if err != nil {
		log.Fatalf("Failed jsonvalue.Unmarshal : %s", err)

		return
	}
	bb, _ := j.GetString("tunnels", 0, "proto")
	cc, _ := j.GetString("tunnels", 0, "public_url")
	if "https" == bb {
		cc = strings.Replace(cc, "https://", "", -1)
	} else if "http" == bb {
		cc = strings.Replace(cc, "http://", "", -1)
	}
	fmt.Println(string(cc))
}

错误为： unrecognized raw text, invalid character \u0065 at Position 246

**Comment by Andrew-M-C** [comment]
嗯这是个 bug，原因是 number 类型没有支持好指数类型的写法。
我本周内出一个 hotfix 版。如果你有时间的话，也欢迎 PR 哈～～～ @gitv2ray

**Comment by Andrew-M-C** [comment]
已经修复了，你可以拉 master 分支试用。我也准备发一个 beta 版

**Comment by gitv2ray** [comment]
感谢大佬修复

**Comment by Andrew-M-C** [comment]
> 感谢大佬修复

不客气不客气，敢开源就得负责好把 bug 修掉，也感谢你的 issue 哈 @gitv2ray
